nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.1.cjs
packageExtensions:
  '@vitejs/plugin-vue@*':
    dependencies:
      'vite': '*'
  '@vitejs/plugin-vue-jsx@*':
    dependencies:
      'vite': '*'
  '@vue/babel-plugin-jsx@*':
    dependencies:
      '@babel/core': '*'
  'ts-node@*':
    dependencies:
      'typescript': '*'
  'vite-plugin-pwa@*':
    dependencies:
      'vite': '*'
  'vue-demi@*':
    dependencies:
      'vue': '*'
