// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    CaptionModelHix: typeof import('./components/caption/ModelHix.vue')['default']
    CaptionModelPpv: typeof import('./components/caption/ModelPpv.vue')['default']
    CaptionModelRainx: typeof import('./components/caption/ModelRainx.vue')['default']
    CaptionModelWpd: typeof import('./components/caption/ModelWpd.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Colorbar: typeof import('./components/Colorbar.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    FakeCard: typeof import('./components/FakeCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ImageModal: typeof import('./components/ImageModal.vue')['default']
    InfoPanel: typeof import('./components/InfoPanel.vue')['default']
    InfoPres: typeof import('./components/info/Pres.vue')['default']
    InfoRain: typeof import('./components/info/Rain.vue')['default']
    InfoTemp: typeof import('./components/info/Temp.vue')['default']
    InfoWind: typeof import('./components/info/Wind.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    LoadingIcon: typeof import('./components/LoadingIcon.vue')['default']
    LonginfoPres: typeof import('./components/longinfo/Pres.vue')['default']
    LonginfoRain: typeof import('./components/longinfo/Rain.vue')['default']
    LonginfoTemp: typeof import('./components/longinfo/Temp.vue')['default']
    LonginfoWind: typeof import('./components/longinfo/Wind.vue')['default']
    MapBox: typeof import('./components/MapBox.vue')['default']
    MapStationSelector: typeof import('./components/MapStationSelector.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Popup: typeof import('./components/Popup.vue')['default']
    PulsatingDot: typeof import('./components/PulsatingDot.vue')['default']
    Range: typeof import('./components/Range.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowGroupBtns: typeof import('./components/RowGroupBtns.vue')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
    SwitchGroup: typeof import('@headlessui/vue')['SwitchGroup']
    SwitchLabel: typeof import('@headlessui/vue')['SwitchLabel']
    ValidationDateSelector: typeof import('./components/ValidationDateSelector.vue')['default']
    WeatherButtons: typeof import('./components/WeatherButtons.vue')['default']
  }
}
