/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Colorbar: typeof import('./components/Colorbar.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    FakeCard: typeof import('./components/FakeCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    IFa6SolidChevronDown: typeof import('~icons/fa6-solid/chevron-down')['default']
    IFa6SolidChevronLeft: typeof import('~icons/fa6-solid/chevron-left')['default']
    IFa6SolidChevronRight: typeof import('~icons/fa6-solid/chevron-right')['default']
    IFa6SolidChevronUp: typeof import('~icons/fa6-solid/chevron-up')['default']
    IFa6SolidCirclePause: typeof import('~icons/fa6-solid/circle-pause')['default']
    IFa6SolidCirclePlay: typeof import('~icons/fa6-solid/circle-play')['default']
    IFa6SolidCloudRain: typeof import('~icons/fa6-solid/cloud-rain')['default']
    IFa6SolidWind: typeof import('~icons/fa6-solid/wind')['default']
    IFaSolidCheck: typeof import('~icons/fa-solid/check')['default']
    IFaSolidCloudUploadAlt: typeof import('~icons/fa-solid/cloud-upload-alt')['default']
    IFaSolidInfo: typeof import('~icons/fa-solid/info')['default']
    IFaSolidThermometerHalf: typeof import('~icons/fa-solid/thermometer-half')['default']
    ImageModal: typeof import('./components/ImageModal.vue')['default']
    IMdiCheckBold: typeof import('~icons/mdi/check-bold')['default']
    IMdiUnfoldMoreHorizontal: typeof import('~icons/mdi/unfold-more-horizontal')['default']
    InfoPanel: typeof import('./components/InfoPanel.vue')['default']
    IWiBarometer: typeof import('~icons/wi/barometer')['default']
    IWiWindDeg: typeof import('~icons/wi/wind-deg')['default']
    Lazy: typeof import('./components/Lazy.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    LoadingIcon: typeof import('./components/LoadingIcon.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    MapBox: typeof import('./components/MapBox.vue')['default']
    ModelCaption: typeof import('./components/ModelCaption.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Popup: typeof import('./components/Popup.vue')['default']
    PulsatingDot: typeof import('./components/PulsatingDot.vue')['default']
    Range: typeof import('./components/Range.vue')['default']
    ReportItemList: typeof import('./components/ReportItemList.vue')['default']
    ReportList: typeof import('./components/ReportList.vue')['default']
    RowGroupBtns: typeof import('./components/RowGroupBtns.vue')['default']
    StationSelector: typeof import('./components/StationSelector.vue')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
    SwitchGroup: typeof import('@headlessui/vue')['SwitchGroup']
    SwitchLabel: typeof import('@headlessui/vue')['SwitchLabel']
    Tab: typeof import('@headlessui/vue')['Tab']
    TabGroup: typeof import('@headlessui/vue')['TabGroup']
    TabList: typeof import('@headlessui/vue')['TabList']
    TabPanel: typeof import('@headlessui/vue')['TabPanel']
    TabPanels: typeof import('@headlessui/vue')['TabPanels']
    UploadReport: typeof import('./components/UploadReport.vue')['default']
    ValidationDateSelector: typeof import('./components/ValidationDateSelector.vue')['default']
    ValidationTabs: typeof import('./components/ValidationTabs.vue')['default']
    WeatherButtons: typeof import('./components/WeatherButtons.vue')['default']
    WeatherDescription: typeof import('./components/WeatherDescription.vue')['default']
    WeatherPopupInfo: typeof import('./components/WeatherPopupInfo.vue')['default']
  }
}
