// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CaptionModelHix: typeof import('./components/caption/ModelHix.vue')['default']
    CaptionModelPpv: typeof import('./components/caption/ModelPpv.vue')['default']
    CaptionModelRainx: typeof import('./components/caption/ModelRainx.vue')['default']
    CaptionModelWpd: typeof import('./components/caption/ModelWpd.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Colorbar: typeof import('./components/Colorbar.vue')['default']
    FakeCard: typeof import('./components/FakeCard.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    InfoPanel: typeof import('./components/InfoPanel.vue')['default']
    InfoPres: typeof import('./components/info/Pres.vue')['default']
    InfoRain: typeof import('./components/info/Rain.vue')['default']
    InfoTemp: typeof import('./components/info/Temp.vue')['default']
    InfoWind: typeof import('./components/info/Wind.vue')['default']
    LoadingIcon: typeof import('./components/LoadingIcon.vue')['default']
    LonginfoPres: typeof import('./components/longinfo/Pres.vue')['default']
    LonginfoRain: typeof import('./components/longinfo/Rain.vue')['default']
    LonginfoTemp: typeof import('./components/longinfo/Temp.vue')['default']
    LonginfoWind: typeof import('./components/longinfo/Wind.vue')['default']
    MapBox: typeof import('./components/MapBox.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Popup: typeof import('./components/Popup.vue')['default']
    PulsatingDot: typeof import('./components/PulsatingDot.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./components/Switch.vue')['default']
    WeatherButtons: typeof import('./components/WeatherButtons.vue')['default']
  }
}

export {}
